# zabbix-agent vars
agent_server:
#agent_listeninterface:
#agent_listenip:
#agent_listenport:
agent_serveracrive:
agent_logfilesize: 100



# zabbix api vars
zabbix_url: "http://192.168.21.73/zabbix/"
zabbix_api_user: Admin
zabbix_api_pass: zabbix
zabbix_api_create_hostgroup: False
zabbix_api_create_hosts: True
zabbix_create_host: present
zabbix_create_hostgroup: present
zabbix_host_status: enabled
zabbix_proxy: null
zabbix_host_groups:
  - Linux servers
zabbix_link_templates:
  - Template OS Linux

agent_interfaces:
  - type: 1
    main: 1
    useip: 1
    ip: "{{ agent_ip }}"
    dns: ""
    port: "10050"